# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c06cba6ab26c18c536f45e89dfc2daf194c0662ae96d6996be57df594179d058ea768aa38a1cc17edcb6970d38b62f52cf128ada29c1243cfdb16e0f8e1f9aae

test:
  secret_key_base: fe30df03e92cf3528b98bdb8991bb361e34dcd61d162ae6c2006ef458b0f433cecdd8e84c2b97e1be5e4573a021623531891344c3d661181c5c47fdf80d0a146

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
